        <div class="manager_info_row">
            <?php include('info_header.phtml'); ?>
            <div class="info_row_body">
            <div id="filterlist">
            <?php if(count($this->elements->getIncludeFilterList()) < 1): ?>
                no filter active
            <?php else:
            foreach($this->elements->getIncludeFilterList() AS $infilter => $infiltervalues):
            ?>
                <div class="active_filter_label" name="<?php echo $infilter; ?>"><?php echo $infilter . ': '; ?></div>
                <div class="active_filter_values" id="<?php echo $infilter; ?>_filter_values">
                    <?php
                    foreach($infiltervalues AS $infiltervalue):
                        ?>
                        <div class="filter_entry" id="<?php echo $infilter; ?>_<?php echo $infiltervalue; ?>">
                        <span><?php echo $infiltervalue; ?></span>
                        <span class="btn_remove_filter fa fa-minus-square-o fa-sm" style="margin-top: 3px"></span>
                        </div>
                        <?php
                    endforeach;
                    ?>
                </div>
                <br />
            <?php
        endforeach;
        ?>

            <?php foreach($this->elements->getIncludeFilterList() AS $infilter => $infiltervalues): ?>
                <input type="hidden" class="filter" name="<?php echo $infilter; ?>" value="<?php echo implode($infiltervalues, ';'); ?>" />
            <?php endforeach; ?>
            <?php endif; ?>
            </div>
            </div>
        </div>


