        <div class="manager_element_body">
        <?php
            list($targetWidth, $targetHeight) = calculateRatioSize($element->getWidth(), $element->getHeight(), 350);

            $imgsrc = 'output/' . $element->getCompanyId() . '/' . $element->getAdvertiserId();
            $imgsrc .= '/0/preview_' . $element->getId() . '_' . $element->getWidth() . 'x' . $element->getHeight() . '.gif';
        ?>
            <div class="manager_element_name">
            <?php echo $element->getName(); ?>
            </div>
            <div class="manager_element_preview">
            <img src="<?php echo $imgsrc; ?>" width="<?php echo $targetWidth; ?>" />
            </div>
            <div class="template_info_box">
            <strong>Categories:</strong><br />
                <?php foreach($element->getCategoryIds() AS $categoryId) :  ?>
                <?php echo $categoryId ?>;
                <?php endforeach; ?>
            </div>
        </div>

