<div id="awesomeEditor" class="row" style="margin-top: 70px; padding-left: 10px; padding-right: 10px;">
    <div class="col-md-7">
        <div class="row" style="margin-left: 5px;">
            <img src="<?php echo $this->gif;?>" alt="">

        </div>
        <div class="row" style="padding-top: 5px; margin-left: 5px;">
            <!--        On click render template and show the change-->
            <button type="submit" class="btn btn-default" form="editor" name="submit" value="preview">Preview</button>
            <!--        On click render template, show the change and save data to database-->
            <button type="submit" class="btn btn-default" form="editor" name="submit" value="save">Save</button>
        </div>
    </div>
    <div class="col-md-5">
        <form id="editor" action="#" method="post">
        <div class="panel-group" id="accordion">
                <?php
                    foreach($this->elements as $element):
                        $type = get_class($element);
                        include($type . '.inc.php');
                    endforeach;
                ?>
            <input type="hidden" name="id" value="<?php echo $this->templateId; ?>">
        </div>
        </form>
     </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $(window).keydown(function(event){
            if(event.keyCode == 13) {
                event.preventDefault();
                return false;
            }
        });
        $('#editor').on('submit', function(e){
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: '/chameleon/ajax/changeSvg.php',
                data: $(this).serialize(),
                success: function(){
//                    location.reload();
                }
            });
        });
        $('.picker').colorpicker();
    });
</script>

