<div id="footer" class="navbar navbar-default navbar-fixed-bottom navbar-inverse" role="navigation">
    <div class="container" style="width: 100%">
        <div class="navbar-header" style="height: 60px;">
            <img class="navbar-brand" src="images/mdlogo_white-border.png.xhtml" style="height: 60px;"/>
        </div>
        <ul class="nav navbar-nav navbar-right">
            <li id="phone">
                <span class="glyphicon glyphicon-earphone"></span>
                <span>+49 821 26841003</span>
            </li>
        </ul>
    </div>
</div>
</body>
</html>
