<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
    <title>mediadecision chameleon</title>
    <meta charset="UTF-8">
    <meta http-equiv="cache-control" content="no-cache">
    <meta http-equiv="cache-control" content="no-store">
    <meta http-equiv="cache-control" content="must-revalidate">
    <script type="text/javascript" src="js/jquery-1.11.1.min.js"></script>
    <script type="text/javascript" src="js/bootstrap.min.js"></script>
    <script type="text/javascript" src="colorpicker/js/bootstrap-colorpicker.js"></script>
    <script type="text/javascript" src="js/fileinput.js"></script>
    <script type="text/javascript" src="js/jquery.imagemapster.js"></script>
    <script type="text/javascript" src="js/mouseover_popup.js"></script>
    <script type="text/javascript" src="js/jquery.blockUI.js"></script>
    <script type="text/javascript" src="js/imagelightbox.js"></script>
    <script type="text/javascript" src="js/jBox.js"></script>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="colorpicker/css/colorpicker.css" />
    <link rel="stylesheet" href="flatstrap/css/custom.css" />
    <link rel="stylesheet" href="css/jBox.css" />
    <link rel="stylesheet" href="css/main.css" />
</head>
<body>
<div id="preview_div" style="position: absolute;"></div>
<div id="topbar" class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <img id="md_logo" class="navbar-brand" src="images/mdlogo_white-border.png" alt="powered by mediadecision" />
        </div>
        <div id="userInformation"><?php echo $auditUserId; ?><br/>username</div>
    </div>
</div>
