<html>
<head>
    <meta charset="UTF-8">
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="colorpicker/js/bootstrap-colorpicker.js"></script>
    <script type="text/javascript" src="js/fileinput.js"></script>
    <script type="text/javascript" src="js/jquery.imagemapster.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery.bootstrapvalidator/0.5.0/js/bootstrapValidator.min.js"></script>
    <script type="text/javascript" src="js/mouseover_popup.js"></script>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jquery.bootstrapvalidator/0.5.0/css/bootstrapValidator.min.css"/>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="colorpicker/css/colorpicker.css">
    <link rel="stylesheet" href="flatstrap/css/custom.css">
    <link rel="stylesheet" href="css/main.css">
</head>
<body>
<div style="display: none; position: absolute; z-index: 110; left: 400; top: 100; width: 15; height: 15" id="preview_div"></div>
<div id="topbar" class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
    <div class="container" style="width: 100%">
        <div class="navbar-header" style="height: 60px;">
            <img class="navbar-brand" src="images/mdlogo_white-border.png.xhtml" style="height: 60px;"/>
        </div>
        <div style="color:#ffffff;text-align:right;padding-top:15px;line-height:15px;height:60px;"><?php echo $auditUserId; ?><br />username</div>
    </div>
</div>
