<?php include('navigation.inc.php');?>

<?php
    if(!is_object($this->elements) || count($this->elements) === 0):
?>
    <p class="notification"><?php echo $this->message; ?></p>
<?php
    else:
?>
<div class="container margin-left-150">
    <div id="managerView">
    <?php
        echo 'Company: ';
        foreach($this->elements->getCompanyIds() AS $companyId):
        echo $companyId . '; ';
        endforeach;
        echo '<br />';
        echo 'Advertiser: ';
        foreach($this->elements->getAdvertiserIds() AS $advertiserId):
        echo $advertiserId . '; ';
        endforeach;
        echo '<br />';
        echo '<br />';
        foreach($this->elements as $key => $element):
    ?>
        - <?php echo $element->getName(); ?>
        <br />
    <?php
        endforeach;
        endif;
    ?>

    <input type="hidden" id="advertiserId" name="advertiserId" value="<?php echo $this->advertiserId; ?>">
    <input type="hidden" id="companyId"  name="companyId" value="<?php echo $this->companyId; ?>">
    </div>
</div>

<script type="text/JavaScript" src="js/overview.js"></script>
