<?php
    include('navigation.inc.php');
?>
<div id="manager_view">
    <div id="manager_company_info">
    </div>
    <div id="manager_advertiser_info">
    </div>
    <div id="manager_category_info">
    </div>
    <div id="manager_active_filters">
    </div>
    <div id="manager_select_filters">
    </div>
</div>

<script type="text/JavaScript" src="js/manager.class.js"></script>

<div style="hidden">
<!-- blablabla -->
<!-- clone  me -->
</div>
