<?php include('navigation.inc.php');?>

<?php
    if(!is_object($this->elements) || count($this->elements) === 0):
?>
    <p class="notification"><?php echo $this->message; ?></p>
<?php
    else:
?>
<div class="container margin-left-150">
    <div id="managerView">
    <?php
        foreach($this->elements as $creative):
    ?>
        <!-- ... -->
    <?php
        endforeach;
        endif;
    ?>

    <input type="hidden" id="advertiserId" name="advertiserId" value="<?php echo $this->advertiserId; ?>">
    <input type="hidden" id="companyId"  name="companyId" value="<?php echo $this->companyId; ?>">
    </div>
</div>

<script type="text/JavaScript" src="js/overview.js"></script>
