    <?php
        if(!is_array($this->previews)):
    ?>
            <h1>An error occurred. Please try reloading the page ...</h1>
    <?php
        else:
    ?>
    <div class="row" style="margin-top: 70px; padding-left: 10px;">
    <?php
        foreach($this->previews as $preview):
    ?>
        <form method="post" action="index.php?page=editor">
            <div class="col-md-3">
                <div>
                    <img src="<?php echo $preview->filepath; ?>" alt="" width="<?php echo $preview->width; ?>">
                </div>
                <input type="hidden" name="id" value="<?php echo $preview->id; ?>">
                <input type="hidden" name="advertiserId" value="<?php echo $preview->advertiserId; ?>">
                <input type="hidden" name="companyId" value="<?php echo $preview->companyId; ?>">
                <input type="hidden" name="templateName" value="<?php echo $preview->templateName; ?>">
                <button type="submit" class="btn btn-default">Edit</button>
            </div>
        </form>
    <?php
        endforeach;
        endif;
    ?>
    </div>




