<?php include('navigation.inc.php');?>

<?php
    if(!is_array($this->previews) || count($this->previews) === 0):
?>
    <p class="notification"><?php echo $this->message; ?></p>
<?php
    else:
?>
<div class="container-fluid" style="margin-left: 150px;">
    <div id="overview" style="margin-top: 75px;">
    <?php
        foreach($this->previews as $preview):
    ?>
            <div id="template_<?php echo $preview->templateId; ?>" class="row template" style="background-color: #F2F2F2;">
                <div class="thumbnail thumbnail-half col-md-2">
                    <div class="overviewTitle">Template</div>
                    <div style="min-height: 215px;">
                        <a href="<?php echo BASE_DIR;?>/index.php?page=editor&templateId=<?php echo $preview->templateId; ?>">
                            <image src="<?php echo $preview->filePath; ?>"
                                   onmouseover="showtrail('<?php echo $preview->filePath; ?>', 'Test',<?php echo $preview->bannerWidth; ?>,
                                   <?php echo $preview->bannerHeight; ?>)"
                                   onmouseout="hidetrail()">
                            </image>
                        </a>
                    </div>

                    <?php include('overviewComponents/facts.inc.php'); ?>
                </div>
                <?php
                    include('overviewComponents/category.inc.php');
                    include('overviewComponents/examples.inc.php');
                    include('overviewComponents/action.inc.php');
                ?>
            </div>
            <div class="modal fade" id="categorySelect-<?php echo $preview->templateId; ?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header imageTitle">
                            <button type="button" class="close" data-dismiss="modal"><span class="glyphicon glyphicon-remove-circle"></span></button>
                            <h4 class="modal-title" id="myModalLabel">Select categories:</h4>
                        </div>
                        <div class="modal-body">
                            <?php include('overviewComponents/categoryAlignment.inc.php'); ?>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal -->
            <input type="hidden" name="templateId" value="<?php echo $preview->templateId; ?>">
            <input type="hidden" name="advertiserId" value="<?php echo $preview->advertiserId; ?>">
            <input type="hidden" name="companyId" value="<?php echo $preview->companyId; ?>">
            <input type="hidden" name="templateName" value="<?php echo $preview->templateName; ?>">

    <?php
        endforeach;
        endif;
    ?>

    </div>
</div>

<script type="text/javascript">
    $(document).ready(function()
    {
        $('#addCategory').click(function(e) {
            var selectedOpts = $('#availableCategory option:selected');
            if (selectedOpts.length == 0) {
                alert("Nothing to move.");
                e.preventDefault();
            }

            $('#assignedCategory').append($(selectedOpts).clone());
            $(selectedOpts).remove();
            e.preventDefault();
        });

        $('#removeCategory').click(function(e) {
            var selectedOpts = $('#assignedCategory option:selected');
            if (selectedOpts.length == 0) {
                alert("Nothing to move.");
                e.preventDefault();
            }

            $('#availableCategory').append($(selectedOpts).clone());
            $(selectedOpts).remove();
            e.preventDefault();
        });

        $('.carousel').carousel({
            interval: 4000
        });

        $('.addCategoryOverview').click(function(e) {
            e.preventDefault();
            var id = $(this).attr('id').split('-');
            var templateId = id[1];
            var advertiserId = id[2];
            var data = {};
            var category = [];

            console.log(id);

            $('#availableCategory-'+templateId).find('option:selected').each(function(i,selected){
                var subscription = {};
                subscription.id = $(selected).val();
                subscription.name = $.trim($(selected).text());

                category.push(subscription);

                var node = '<option value="' + subscription.id + '">' + subscription.name + '</option>';
                $('#assignedCategory-'+templateId).append(node);
                $('#availableCategory-'+templateId).find("option[value='"+subscription.id+"']").remove();
            });

            data.category = category;
            data.advertiserId = advertiserId;
            data.templateId   = templateId;

            data.companyId    = $('#companyId').attr('value');
            $.ajax({
                type: "POST",
                data: data,
                dataType: "json",
                url: "/chameleon/ajax/addCategory.php"
            }).done(function(){
            }).fail(function(){

            });
        });

        $('.removeCategoryOverview').click(function(e) {
            e.preventDefault();

            var id = $(this).attr('id').split('-');
            var templateId = id[1];
            var advertiserId = id[2];
            var data = {};
            var category = [];

            $('#assignedCategory-'+templateId).find('option:selected').each(function(i,selected){
                var subscription = {};
                subscription.id = $(selected).val();
                subscription.name = $.trim($(selected).text());

                category.push(subscription);

                $("#assignedCategory-"+templateId).find("option[value='"+subscription.id+"']").remove();
                var node = '<option value="' + subscription.id + '">'+subscription.name+'</option>';
                $('#availableCategory-'+templateId).append(node);
            });

            data.category = category;
            data.advertiserId = advertiserId;
            data.templateId   = templateId;
            data.companyId    = $('#companyId').attr('value');
            $.ajax({
                type: 'POST',
                data: data,
                dataType: "json",
                url:  '/chameleon/ajax/removeCategory.php'
            }).done(function(){
            }).fail(function(){
            });
        });

        $(".cloneTemplate").click(function(){

            var id = $(this).attr('id').split('-');
            var templateId = id[1];
            var advertiserId = id[2];
            var companyId = id[3];
            var data = {};

            data.advertiserId = advertiserId;
            data.templateId   = templateId;

            $.ajax({
                type: 'POST',
                data: data,
                dataType: "json",
                url:  '/chameleon/ajax/cloneTemplate.php',
                success: function(response){

                    console.log(response);

                    var url = window.location.origin + '/chameleon/index.php?page=editor&templateId=' + response.idBannerTemplate +
                        '&companyId=' + companyId + '&advertiserId=' + advertiserId;
                    window.location.replace(url);
                }
            });
        })


    });
</script>
