<?php include('navigation.inc.php');?>

<?php
    if(!is_array($this->previews) || count($this->previews) === 0):
?>
    <p class="notification"><?php echo $this->message; ?></p>
<?php
    else:
?>
<div class="container-fluid" style="margin-left: 150px;">
    <div id="nodes" class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation" style="margin-top:61px;
margin-left:161px;background-color: #888888; border-color: #888888;">
        <ul class="nav navbar-nav navbar-left">
            <li style="padding: 14px;">
                <?php
                    if(!empty($_SESSION['categories'])):
                ?>
                    Content of session shown
                <?php
                    else:
                ?>
                    No categories selected
                <?php
                    endif;
                ?>
                <button id="editCategories" type="button" class="btn btn-xs" data-toggle="modal" data-target="#cmeoModal"
                        style="background-color:
                #888888;">
                    <span class="glyphicon glyphicon-pencil"></span>
                </button>
            </li>
        </ul>
    </div>

    <div id="overview" class="row" style="margin-top: 120px;">
    <?php
        foreach($this->previews as $preview):
    ?>

            <div id="template_<?php echo $preview->templateId; ?>" class="row">
                <div class="thumbnail thumbnail-half col-md-2">
                    <div class="overviewTitle">Template</div>
                    <image class="preview" src="<?php echo $preview->filePath; ?>">
                    <?php include('overviewComponents/facts.inc.php'); ?>
                </div>
                <?php

                    include('overviewComponents/categoryAlignment.inc.php');
                    include('overviewComponents/examples.inc.php');
                    include('overviewComponents/action.inc.php');
                ?>
            </div>
            <input type="hidden" name="templateId" value="<?php echo $preview->templateId; ?>">
            <input type="hidden" name="advertiserId" value="<?php echo $preview->advertiserId; ?>">
            <input type="hidden" name="companyId" value="<?php echo $preview->companyId; ?>">
            <input type="hidden" name="templateName" value="<?php echo $preview->templateName; ?>">


    <?php
        break;
        endforeach;
        endif;
    ?>

    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="cmeoModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header textTitle">
                <button type="button" class="close" data-dismiss="modal"><span class="glyphicon glyphicon-remove-circle"></span></button>
                <h4 class="modal-title" id="myModalLabel">Select category:</h4>
            </div>
            <div class="modal-body">
                <form role="form">
                        <?php include('categories.inc.php'); ?>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function()
    {
        $('#addCategory').click(function(e) {
            var selectedOpts = $('#availableCategory option:selected');
            if (selectedOpts.length == 0) {
                alert("Nothing to move.");
                e.preventDefault();
            }

            $('#assignedCategory').append($(selectedOpts).clone());
            $(selectedOpts).remove();
            e.preventDefault();
        });

        $('#removeCategory').click(function(e) {
            var selectedOpts = $('#assignedCategory option:selected');
            if (selectedOpts.length == 0) {
                alert("Nothing to move.");
                e.preventDefault();
            }

            $('#availableCategory').append($(selectedOpts).clone());
            $(selectedOpts).remove();
            e.preventDefault();
        });

        $('.carousel').carousel({
            interval: 4000
        });

        $('.addCategoryOverview').click(function(e) {
            var id = $(this).attr('id').split('-');
            var data = {};
            var categoryId    = $('#availableCategory').find(':selected').val();
            var categoryName  = $.trim($('#availableCategory').find(':selected').text());
            data.advertiserId = id[2];
            data.templateId   = id[1];
            data.categoryId   = categoryId;
            data.categoryName = categoryName;
            data.companyId    = $('#companyId').attr('value');
            $.ajax({
                type: "POST",
                data: data,
                dataType: "json",
                url: "/chameleon/ajax/addCategory.php"
            }).done(function(){
            }).fail(function(){
            });
        });

        $('.removeCategoryOverview').click(function(e) {
            var id = $(this).attr('id').split('-');
            var data = {};
            var categoryId    = $('#assignedCategory').find(':selected').val();
            var categoryName  = $.trim($('#assignedCategory').find(':selected').text());
            data.advertiserId = id[2];
            data.templateId   = id[1];
            data.categoryId   = categoryId;
            data.categoryName = categoryName;
            data.companyId    = $('#companyId').attr('value');
            $.ajax({
                type: 'POST',
                data: data,
                dataType: "json",
                url:  '/chameleon/ajax/removeCategory.php'
            }).done(function(){
            }).fail(function(){
            });
        })
    });
</script>
